#ifndef __UNIVERSUM_LIB_TYPE_BASE_GEOMETRIE_TYPE_H
#define __UNIVERSUM_LIB_TYPE_BASE_GEOMETRIE_TYPE_H

enum class BaseGeometrieType {
	PLANE,
	ENTRY_COUNT,
};

#endif //__UNIVERSUM_LIB_TYPE_BASE_GEOMETRIE_TYPE_H