#ifndef __UNIVERSUM_LIB_TYPE_GEOMETRIE_DATA_TYPE_H
#define __UNIVERSUM_LIB_TYPE_GEOMETRIE_DATA_TYPE_H

namespace UniLib {
	enum class GeometrieDataType {
		NONE = 0,
		VERTICES = 1,
		COLORS = 2,
		NORMALS = 4,
		TEX2D_1 = 8,
		TEX2D_2 = 16,
		TEX2D_3 = 32,
		TEX2D_4 = 64,
		VECTOR3D = VERTICES + NORMALS,
		VECTOR2D = TEX2D_1 + TEX2D_2 + TEX2D_3 +TEX2D_4,
		VECTOR4D = COLORS,
		ENTRY_COUNT = 128
	};
}

#endif //__UNIVERSUM_LIB_TYPE_GEOMETRIE_DATA_TYPE_H