#ifndef __UNIVERSUM_LIB_TYPE_GEOMETRIE_RENDER_MODE_H
#define __UNIVERSUM_LIB_TYPE_GEOMETRIE_RENDER_MODE_H

namespace UniLib {
	enum class GeometrieRenderMode {
		POINTS,
		LINES,
		LINE_STRIP,
		LINE_LOOP,
		TRIANGLES,
		TRIANGLE_STRIP,
		TRIANGLE_FAN,
		ENTRY_COUNT
	};
}

#endif //__UNIVERSUM_LIB_TYPE_GEOMETRIE_RENDER_MODE_H